// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkx-Vbh1dOvYEMm7kYaTe60TCs8c0xKA',
    appId: '1:135416020443:web:4c9310ef4756a0e2e27bfe',
    messagingSenderId: '135416020443',
    projectId: 'newpro-61c26',
    authDomain: 'newpro-61c26.firebaseapp.com',
    storageBucket: 'newpro-61c26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCstIi7fSoNLvefmCFMPslrx851v0nNEdc',
    appId: '1:135416020443:android:a5700959f42253e8e27bfe',
    messagingSenderId: '135416020443',
    projectId: 'newpro-61c26',
    storageBucket: 'newpro-61c26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatYph9tNXwMLRo6q9kIeJCEMQjkuExKk',
    appId: '1:135416020443:ios:53fe908cff757edfe27bfe',
    messagingSenderId: '135416020443',
    projectId: 'newpro-61c26',
    storageBucket: 'newpro-61c26.appspot.com',
    iosClientId: '135416020443-engjuq4bfnupmesdn35e1p00kn24mntm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ad2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDatYph9tNXwMLRo6q9kIeJCEMQjkuExKk',
    appId: '1:135416020443:ios:b35be265ac12c586e27bfe',
    messagingSenderId: '135416020443',
    projectId: 'newpro-61c26',
    storageBucket: 'newpro-61c26.appspot.com',
    iosClientId: '135416020443-p972d46ffpj2c1q8frtgfhgnkd1129mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ad2.RunnerTests',
  );
}
